title: My GitHub Blog
author: pedecee
email: pedecee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub Blog of pedecee.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
pedecee:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
